trigger:
  batch: true
  branches:
    include:
      - main

pr: [main]

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: publishPackage
    displayName: 🚀 Publish
    type: boolean
    default: false

extends:
  template: azure-pipelines/npm-package/pipeline.yml@templates
  parameters:
    npmPackages:
      - name: gulp-vinyl-zip
        buildSteps:
          - script: npm ci
        testPlatforms:
          - name: Linux
            nodeVersions: [18.x, 20.x, 22.x]
          - name: MacOS
            nodeVersions: [18.x, 20.x, 22.x]
          - name: Windows
            nodeVersions: [18.x, 20.x, 22.x]
        testSteps:
          - script: npm ci
          - script: npm run lint
            condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
          - script: npm test
        publishPackage: ${{ parameters.publishPackage }}